/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as FavoritesRouteImport } from "./routes/favorites"
import { Route as CheckoutRouteImport } from "./routes/checkout"
import { Route as CartRouteImport } from "./routes/cart"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PersonasPersonaIdRouteImport } from "./routes/personas/$personaId"

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: "/favorites",
  path: "/favorites",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasPersonaIdRoute = PersonasPersonaIdRouteImport.update({
  id: "/personas/$personaId",
  path: "/personas/$personaId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/cart": typeof CartRoute
  "/checkout": typeof CheckoutRoute
  "/favorites": typeof FavoritesRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/personas/$personaId": typeof PersonasPersonaIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/cart": typeof CartRoute
  "/checkout": typeof CheckoutRoute
  "/favorites": typeof FavoritesRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/personas/$personaId": typeof PersonasPersonaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/cart": typeof CartRoute
  "/checkout": typeof CheckoutRoute
  "/favorites": typeof FavoritesRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/personas/$personaId": typeof PersonasPersonaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/cart"
    | "/checkout"
    | "/favorites"
    | "/login"
    | "/register"
    | "/personas/$personaId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/cart"
    | "/checkout"
    | "/favorites"
    | "/login"
    | "/register"
    | "/personas/$personaId"
  id:
    | "__root__"
    | "/"
    | "/cart"
    | "/checkout"
    | "/favorites"
    | "/login"
    | "/register"
    | "/personas/$personaId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PersonasPersonaIdRoute: typeof PersonasPersonaIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/favorites": {
      id: "/favorites"
      path: "/favorites"
      fullPath: "/favorites"
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/checkout": {
      id: "/checkout"
      path: "/checkout"
      fullPath: "/checkout"
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cart": {
      id: "/cart"
      path: "/cart"
      fullPath: "/cart"
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/personas/$personaId": {
      id: "/personas/$personaId"
      path: "/personas/$personaId"
      fullPath: "/personas/$personaId"
      preLoaderRoute: typeof PersonasPersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PersonasPersonaIdRoute: PersonasPersonaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
